openapi: 3.0.3
info:
  title: Olympia
  version: '1.0.0'
servers:
  - url: /api
paths:
  /topThreeAtheltes/{sport}:
    get:
      description: Returns a list of top athletes according to gender
      responses:
        200:
          description: Successfully retrieved a list of top atheltes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopThreeAthletesType'
        500:
          description: Internal server error
  /fullResults/{sport}/{gender}:
    get:
      description: Returns a list of full results based on sport and gender
      responses:
        200:
          description: Successfully retrieved full results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SportResultType'
        500:
          description: Internal server error
  /medalTable:
    get:
      description: Lists medalists for medal table
      responses:
        200:
          description: Successfully retrieved all medalists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedalistType'
        500:
          description: Internal server error
components:
  schemas:
    ClientSchema:
      type: object
      properties:
        client_id:
          type: integer
          format: int64
        client_ident:
          type: string
          description: Used as an alternative name for the client
          example: AVA
        client_name:
          type: string
          description: The name of the client, used as alt text when image can't be found
          example: 'Avacon'
        client_logopath:
          type: string
          description: The path where the client's logo is saved
          example: '/assets/avaLogo.png'
        client_color:
          type: string
          description: A color of the brand defined for each client
          example: '#86BC25'
    ModuleSchema:
      type: object
      properties:
        module_id:
          type: integer
          format: int64
        module_ident:
          type: string
          description: Used as an alternative name for the module
          example: FreewayApp
        module_name:
          type: string
          description: The name of the module
          example: Baustraßen-Tool
        module_url:
          type: string
          description: The link where you can find the module
        module_visible:
          type: boolean
          description: Represents visibilty for other clients
        module_freelogin:
          type: boolean
          description: Is module free to use without login
        module_priority:
          type: integer
          format: int64
          description: The priority of the module
        module_activated:
          type: integer
          description: Shows whether the module is activated
    ClientModuleSchema:
      type: object
      properties:
        client:
          $ref: '#/components/schemas/ClientSchema'
        modules:
          type: array
          items:
            $ref: '#/components/schemas/ModuleSchema'
    HeaderPropertySchema:
      type: object
      properties:
        header_id:
          type: integer
          format: int64
        header_ident:
          type: string
          description: Ident of the header
          example: EON
        header_user_name:
          type: string
          description: The name of the user
          example: Landingpage
        header_user_logopath:
          type: string
          description: The path where the user's logo is saved
        header_project_title:
          type: string
          description: The title of the project
          example: Landingpage
        header_project_logopath:
          type: string
          description: The path where the project's logo is saved
    GroupSchema:
      type: object
      properties:
        roles:
          type: array
          items:
            type: string
          description: Groups assigned to the client
          example: AVA
